print("Hola a todos.")
print("En esta página lo ayudaremos a sumar, restar, multiplicar y dividir números enteros.")
primero=int(input())
segundo=int(input())
print("La resta de estos números es: ", (primero-segundo))
print( "La suma de estos números es: ", (primero+segundo))
print("La multiplicación de estos números es: ", (primero*segundo))
print("La division entre estos dos números es: ", (primero/segundo))
